### ISSUE TITLE
Problem: Missing Unit Test case for a few projections

### ISSUE THREAD

**Issue by cdc-Hitesh** [crypto-com/chain-indexing#221]
Adding unit test cases for:

- [x] blockevent ,`appinterface/projection/blockevent`  PR: #222 
- [x] validator , `appinterface/projection/validator`  PR: #233 
- [x] validatorstats, `appinterface/projection/validatorstats` PR: #234
